worker_processes auto;
events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Required for WebSocket proxying
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server {
        listen 8188;

        location / {
            proxy_pass         http://127.0.0.1:8189;
            proxy_http_version 1.1;
            proxy_set_header   Upgrade $http_upgrade;
            proxy_set_header   Connection $connection_upgrade;
            proxy_set_header   Host $host;
            proxy_connect_timeout 1s;
            proxy_send_timeout    300s;
            proxy_read_timeout    300s;

            error_page 502 503 =200 @init_page;
        }

        location @init_page {
            root      /opt/init-page;
            try_files /index.html =404;
            add_header Cache-Control "no-cache, no-store";
        }
    }
}
